apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-jobs
  namespace: test
spec:
  interval: 5m
  url: https://github.com/bkuzmic/flux-jobs
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-jobs
  namespace: test
spec:
  interval: 10m
  targetNamespace: test
  sourceRef:
    kind: GitRepository
    name: flux-jobs
  path: "./flux"
  prune: true