apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: error-rate
  namespace: test
spec:
  provider:
    address: http://flagger-prometheus.flagger:9090
    type: prometheus
  query: |
    100 - rate(
      http_requests_total{
        kubernetes_namespace="{{ namespace }}",
        app="{{ target }}",
        status!~"5.*"
      }[{{ interval }}]) 
    / 
    rate(
      http_requests_total{
        kubernetes_namespace="{{ namespace }}",
        app="{{ target }}"
      }[{{ interval }}]
    ) * 100